config/routes.rb
Rails.application.routes.draw do
    get '/pages/about' => 'pages#about', as: :about
    get '/pages/contact' => 'pages#contact', as: :contact

    # get 'posts' => 'posts#index', as: :posts
    # post '/posts' => 'posts#create'
    #
    # get '/post/:id' => 'posts#show', as: :post
    # patch '/post/:id' => 'posts#update'
    # delete '/post/:id' => 'posts#destroy'
    #
    # get 'posts/new' => 'posts#new', as: :new_post
    #
    # get '/post/:id/edit' => 'posts#edit', as: :edit_post
    root "posts#index"
    resources :posts do
        resources :comments
    end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :name, presence: true
    validates :body, presence: true

    validates :name, length: {minimum:2}
    validates :body, length: {minimum:10}
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true

    validates :title, length: {minimum:5}
    validates :body, length: {minimum:20}

    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        flash[:notice] = 'Kommentaren skapades utan problem'

        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        flash[:notice] = 'Kommentaren raderades utan problem'
        redirect_to post_path(@post)

    end

    private
    def comment_params
        params.require(:comment).permit(:name, :body)

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about

    end

    def contact

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]

    def index
        @posts = Post.all.order('created_at DESC')

    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            flash[:notice] = 'Inlägget skapades utan problem'
            redirect_to post_path(@post)
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @post.update(post_params)
            flash[:notice] = 'Inlägget uppdaterades utan problem'
            redirect_to post_path(@post)
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        flash[:notice] = 'Inlägget raderades utan problem'
        redirect_to posts_path
    end



    private

    def find_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comments">
    <h4><%= comment.name %></h4>

    <p>
        <%= comment.body %>
    </p>
    <%= link_to 'Radera', [comment.post, comment], method: :delete, data: {confirm: 'Är du säker?'}%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav>
          <ul>
              <li>Hem</li>
              <li>Om mig</li>
              <li>Portfolio</li>
          </ul>
      </nav>
      <% if flash[:notice] %>
      <div class="notice">
          <%= flash[:notice]%>
      </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hi, welcome to the about page</h1>

<%= link_to("About", about_path)%>
<%= link_to("Contact", contact_path)%>

<%= image_tag('cat.jpg') %>

app/views/pages/contact.html.erb
<h1>Hi, welcome to the contact page</h1>

<%= link_to("About", about_path)%>
<%= link_to("Contact", contact_path)%>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
<ul>
    <% @post.errors.full_messages.each do |message|%>
    <li>
    <%= message %>
</li>
    <% end %>
</ul>
<% end %>

<%= form_for @post do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>

    <%= f.label :body %><br>
    <%= f.text_area :body %><br>

    <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>This is the edit page for <%= params[:id]%> <%= link_to 'back', posts_path %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 class="headline">Hej, välkommen till min blogg </h1>
<span class="addPost"><%= link_to 'New post', new_post_path%></span>


<% @posts.each do |post| %>
<div class="post">
    <h2 class="title"><%= link_to post.title, post_path(post) %></h2>
    <p>
        <%= post.body %>
    </p>
<p class="editDel">
    <%= link_to 'Redigera', edit_post_path(post) %>     <%= link_to 'Radera', post_path(post), method: :delete, data: {confirm: "Är du säker på att du vill ta bort det här inlägget?"} %>

</p>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>Skapa nytt blogginlägg <%= link_to 'back', posts_path %></h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1>This is the show template <%= params[:id] %> <%= link_to 'back', posts_path %></h1>

<p>
    <%= @post.title %>
</p>

<p>
     <%= @post.body %>
</p>
<p>
    <%= link_to 'edit', edit_post_path(@post) %> <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Är du säker på att du vill ta bort det här inlägget?"} %>
</p>

<h2>Kommentera</h2>
<%= form_for [@post, @post.comments.build] do |f| %>
<%= f.label :name %> <br>
<%= f.text_field :name %> <br>
<%= f.label :body %> <br>
<%= f.text_area :body %> <br>
<%= f.submit %>
<% end %>

<h2>Kommentarer:</h2>
<%= render @post.comments.order("created_at DESC") %>